name: 'Installation Environnement'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
  # Installation et mise en place de VisualStudio
  - name: install visual studio
    shell: powershell
    run: |
      curl "https://download.visualstudio.microsoft.com/download/pr/7e1f1b8d-73fe-448c-a4e0-0ea481025985/a327fa967a032896e6408255db82a987a5bf91b42be26c2eaa71ebdadb0f46b8/vs_Professional.exe" -o "vs_Professional.exe" 
      Start-Process -FilePath vs_Professional.exe -ArgumentList "--add", "Microsoft.VisualStudio.Workload.NativeDesktop", "--includeRecommended", "--remove", "Microsoft.VisualStudio.Component.Vcpkg", "--quiet", "--wait" -Wait -PassThru

  - uses: ilammy/msvc-dev-cmd@v1
    with:
      toolset: 14.39

  # Installation de CUDA
  - uses: Jimver/cuda-toolkit@v0.2.23
    id: cuda-toolkit
    with:
      #use-github-cache: false
      cuda: '12.1.0'

