# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  workflow_dispatch:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019
    
    steps:
    - name: before
      run: Get-PSDrive
       # Installation et mise en place de VisualStudio
    - name: install visual studio
      run: |
        curl "https://download.visualstudio.microsoft.com/download/pr/7e1f1b8d-73fe-448c-a4e0-0ea481025985/a327fa967a032896e6408255db82a987a5bf91b42be26c2eaa71ebdadb0f46b8/vs_Professional.exe" -o "vs_Professional.exe" 
        Start-Process -FilePath vs_Professional.exe -ArgumentList "--add", "Microsoft.VisualStudio.Workload.NativeDesktop", "--includeRecommended", "--remove", "Microsoft.VisualStudio.Component.Vcpkg", "--quiet", "--wait" -Wait -PassThru
    - name: after
      run: Get-PSDrive
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.39
    - name: variables
      run: |
        $env:CommandPromptType
        $env:DevEnvDir
        $env:ExtensionSdkDir
        $env:EXTERNAL_INCLUDE
        $env:Framework40Version
        $env:FrameworkDir
        $env:FrameworkDIR64
        $env:FrameworkVersion
        $env:FrameworkVersion64
        $env:INCLUDE
        $env:LIB
        $env:LIBPATH
        $env:NETFXSDKDir
        $env:Path
        $env:Platform
        $env:UCRTVersion
        $env:UniversalCRTSdkDir
        $env:VCIDEInstallDir
        $env:VCINSTALLDIR
        $env:VCToolsInstallDir
        $env:VCToolsRedistDir
        $env:VCToolsVersion
        $env:VisualStudioVersion
        $env:VS170COMNTOOLS
        $env:VSCMD_ARG_app_plat
        $env:VSCMD_ARG_HOST_ARCH
        $env:VSCMD_ARG_TGT_ARCH
        $env:VSCMD_ARG_VCVARS_VER
        $env:VSCMD_VER
        $env:VSINSTALLDIR
        $env:WindowsLibPath
        $env:WindowsSdkBinPath
        $env:WindowsSdkDir
        $env:WindowsSDKLibVersion
        $env:WindowsSdkVerBinPath
        $env:WindowsSDKVersion
        $env:WindowsSDK_ExecutablePath_x64
        $env:WindowsSDK_ExecutablePath_x86
        $env:__DOTNET_ADD_64BIT
        $env:__DOTNET_PREFERRED_BITNESS
        $env:__VSCMD_PREINIT_PATH

