name: Docker

on:
  workflow_dispatch:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019
    
    steps:
    # Installation et mise en place de VisualStudio
    - name: docker
      run: |
        docker pull mcr.microsoft.com/windows/servercore:ltsc2019
        docker run --rm mcr.microsoft.com/windows/servercore:ltsc2019
