name: Docker

on:
  workflow_dispatch:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019
    
    steps:
    # Installation et mise en place de VisualStudio
    - name: before
      run: Get-PSDrive
    - name: docker
      run: |
        docker login -u "${{ secrets.JF_USER }}" "${{ secrets.JF_URL }}" -p "${{ secrets.JF_PASSWORD }}"
        docker pull triala4ty94.jfrog.io/docker/cuda:latest

    #- name: Run the build process with Docker
     # uses: addnab/docker-run-action@v3
      #with:
       #   image: triala4ty94.jfrog.io/docker/cuda:latest
        #  run: |
         #   nvcc -V
    - name: run
      run: docker run triala4ty94.jfrog.io/docker/cuda curl "https://download.visualstudio.microsoft.com/download/pr/7e1f1b8d-73fe-448c-a4e0-0ea481025985/a327fa967a032896e6408255db82a987a5bf91b42be26c2eaa71ebdadb0f46b8/vs_Professional.exe" -o "vs_Professional.exe"; ls

    - name: after
      run: Get-PSDrive
