# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Linux

on:
  workflow_dispatch:
  workflow_call:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"



jobs:
  my-peanut-butter-job:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: abcd 
      run: |
        echo "This is another test" >> test.txt
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "github actions test"
        git push
    - name: Generate list using Markdown
      run: |
        echo "This is the lead in sentence for the list" >> summary
        echo "TEST = ${{ secrets.TEST }}" >> summary # this is a blank line
        echo "- Lets add a bullet point" >> summary
        echo "- Lets add a second bullet point" >> summary
        echo "- How about a third one?" >> summary
        cat summary >> $GITHUB_STEP_SUMMARY


