# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Linux

on:
  workflow_dispatch:
  workflow_call:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"



jobs:
  my-peanut-butter-job:

    runs-on: ubuntu-22.04

    steps:
    - name: Install all packages
      shell: bash
      run: |
        sudo apt-get install linux-libc-dev gdb pax-utils ccache pkg-config -y
    - name: Install CUDA
      shell: bash
      run: |
        sudo apt-key del 7fa2af80
        wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update; sudo apt-get install cuda-toolkit-12-1 -y
        echo "/usr/local/cuda-12.1/bin" >> "$GITHUB_PATH"
    - name: test
      run: |
        sudo rm -rf /opt/nvidia
    - name: pwsh
      run: pwsh --version
    - name: Add mask
      shell: bash
      run: |
        echo "::add-mask::filthyfansofpeanutbutter.com"
        echo "filthyfansofpeanutbutter.com"
    - name: Generate list using Markdown
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "TEST = ${{ secrets.TEST }}" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY


