# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Linux

on:
  workflow_dispatch:
  workflow_call:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"



jobs:
  my-peanut-butter-job:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        ls /opt
    - name: pwsh
      run: pwsh --version
    - name: Add mask
      shell: bash
      run: |
        echo "::add-mask::filthyfansofpeanutbutter.com"
        echo "filthyfansofpeanutbutter.com"
    - name: Generate list using Markdown
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "TEST = ${{ secrets.TEST }}" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY


