# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Linux

on:
  workflow_dispatch:

env:
  VCPKG_ROOT:  '${{ github.workspace }}/../vcpkg'
  VCPKG_COMMIT: "782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa"



jobs:
  my-peanut-butter-job:

    runs-on: ubuntu-latest

    steps:
    - name: Generate list using Markdown
      run: |
        "This is the lead in sentence for the list" >> $env:GITHUB_STEP_SUMMARY
        "" >> $env:GITHUB_STEP_SUMMARY # this is a blank line
        "- Lets add a bullet point" >> $env:GITHUB_STEP_SUMMARY
        "- Lets add a second bullet point" >> $env:GITHUB_STEP_SUMMARY
        "- How about a third one?" >> $env:GITHUB_STEP_SUMMARY


