name: Creation of a release branch

on:
  workflow_dispatch:
  create:

jobs:
  test:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          git branch -a
          echo "Hello world"
