name: test env

on:
  workflow_dispatch:

env:
  CONFIG_ARGS: "bouh"
  
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: test
        shell: bash
        run: | 
          echo "$CONFIG_ARGS"
          echo "CONFIG_ARGS=baaa" >> $GITHUB_ENV
      - name: print
        run: | 
          echo "$CONFIG_ARGS"
          
